//! Linux: `ip` / `resolvectl` driven configuration of a `tunN` interface.
//!
//! The configurator itself is platform independent (it only issues commands
//! through a [`CommandRunner`]) so its command sequences are unit-tested on
//! every OS; only [`super::system_configurator`] selects it on Linux.
//!
//! Commands issued by [`LinuxConfigurator::apply`] (in order):
//!
//! 1. `ip -4 addr show dev tunN` to check whether tun-rs already assigned the
//!    address (it does, via `SIOCSIFADDR`); if not:
//!    `ip addr add <guest> peer <gateway>/<prefix> dev tunN`.
//! 2. `ip link set dev tunN mtu <mtu> up` (idempotent).
//! 3. `ip route add <cidr> dev tunN` for every route (`0.0.0.0/1` and
//!    `128.0.0.0/1` in [`RouteMode::Full`], the given prefixes in
//!    [`RouteMode::Custom`]). A route that already exists (stale, from a
//!    crashed run) is replaced with `ip route replace <cidr> dev tunN`.
//! 4. When DNS is requested, `resolvectl status` decides between two
//!    backends:
//!    * systemd-resolved running: `resolvectl dns tunN <dns>`,
//!      `resolvectl domain tunN ~.`, `resolvectl default-route tunN yes`
//!      (the tunnel resolver becomes the preferred one for every domain).
//!    * otherwise `/etc/resolv.conf` is rewritten: the current file is first
//!      copied to [`RESOLV_BACKUP`] (unless a backup already exists, in
//!      which case that older copy is the real original and is kept), then
//!      `tee /etc/resolv.conf` receives a `nameserver <dns>` stanza on stdin.
//!      `cp`/`tee` write *through* a symlinked `/etc/resolv.conf` rather than
//!      replacing the link.
//!
//! [`LinuxConfigurator::revert`] undoes the steps in reverse order: DNS first
//! (`resolvectl revert tunN`, or `cp -f <backup> /etc/resolv.conf` +
//! `rm -f <backup>`), then `ip route del <cidr> dev tunN` for each route
//! (last added first). The address disappears with the device itself when
//! the tun fd is closed.
//!
//! Everything must run as root; [`crate::requires_root`] is `true` on Linux.

use anyhow::{anyhow, Context, Result};
use netm_proto::TunnelConfig;

use super::{CommandRunner, PlatformConfigurator};
use crate::RouteMode;

/// Where the original `/etc/resolv.conf` is kept while the tunnel is up
/// (fallback DNS backend only).
pub const RESOLV_CONF: &str = "/etc/resolv.conf";
/// Backup path for [`RESOLV_CONF`].
pub const RESOLV_BACKUP: &str = "/etc/resolv.conf.netm-backup";

/// Routes (CIDR strings) to install for `routes`.
pub fn route_cidrs(routes: &RouteMode) -> Vec<String> {
    match routes {
        RouteMode::Full => vec!["0.0.0.0/1".to_string(), "128.0.0.0/1".to_string()],
        RouteMode::Custom(nets) => nets.iter().map(|n| n.trunc().to_string()).collect(),
    }
}

/// Does `ip -4 addr show dev <tun>` output list `inet <ip>[/prefix]`?
pub fn ip_addr_has_inet(output: &str, ip: std::net::Ipv4Addr) -> bool {
    let ip = ip.to_string();
    let mut toks = output.split_whitespace();
    while let Some(t) = toks.next() {
        if t == "inet" {
            if let Some(addr) = toks.next() {
                let addr = addr.split('/').next().unwrap_or(addr);
                if addr == ip {
                    return true;
                }
            }
        }
    }
    false
}

/// Contents written to `/etc/resolv.conf` by the fallback DNS backend.
pub fn resolv_conf_contents(dns: std::net::Ipv4Addr) -> String {
    format!(
        "# Generated by netm (guest tunnel); the original file is saved at {RESOLV_BACKUP}\n\
         # and restored when netm exits.\n\
         nameserver {dns}\n\
         options timeout:2 attempts:2\n"
    )
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum Undo {
    Route { cidr: String, tun: String },
    ResolvectlDns { tun: String },
    ResolvConf,
}

/// [`PlatformConfigurator`] for Linux. Generic over the [`CommandRunner`] so
/// the exact commands can be asserted in tests.
pub struct LinuxConfigurator<R: CommandRunner> {
    runner: R,
    undo: Vec<Undo>,
    reverted: bool,
}

impl<R: CommandRunner> LinuxConfigurator<R> {
    pub fn new(runner: R) -> Self {
        Self {
            runner,
            undo: Vec::new(),
            reverted: true,
        }
    }

    fn run_ok(&mut self, program: &str, args: &[&str], stdin: Option<&str>) -> Result<String> {
        let out = self
            .runner
            .run(program, args, stdin)
            .with_context(|| format!("failed to execute `{program}`"))?;
        if !out.success {
            return Err(anyhow!(
                "`{program} {}` failed: {}",
                args.join(" "),
                out.stderr.trim()
            ));
        }
        Ok(out.stdout)
    }

    /// `true` when the command ran and exited successfully.
    fn succeeds(&mut self, program: &str, args: &[&str]) -> bool {
        matches!(self.runner.run(program, args, None), Ok(out) if out.success)
    }

    fn ensure_address(&mut self, tun: &str, cfg: &TunnelConfig) -> Result<()> {
        let already = match self
            .runner
            .run("ip", &["-4", "addr", "show", "dev", tun], None)
        {
            Ok(out) if out.success => ip_addr_has_inet(&out.stdout, cfg.guest_ip),
            _ => false,
        };
        if already {
            tracing::debug!(tun, ip = %cfg.guest_ip, "address already assigned by tun device");
        } else {
            let guest = cfg.guest_ip.to_string();
            let peer = format!("{}/{}", cfg.gateway_ip, cfg.prefix_len);
            self.run_ok(
                "ip",
                &["addr", "add", &guest, "peer", &peer, "dev", tun],
                None,
            )
            .context("assigning tunnel address")?;
        }
        let mtu = cfg.mtu.to_string();
        self.run_ok("ip", &["link", "set", "dev", tun, "mtu", &mtu, "up"], None)
            .context("bringing tunnel interface up")?;
        Ok(())
    }

    fn add_route(&mut self, cidr: &str, tun: &str) -> Result<()> {
        let args = ["route", "add", cidr, "dev", tun];
        let out = self
            .runner
            .run("ip", &args, None)
            .context("executing `ip route add`")?;
        if out.success {
            return Ok(());
        }
        if out.stderr.contains("exists") {
            // Stale route from a crashed run: replace it.
            tracing::warn!(cidr, "route already exists; replacing it");
            self.run_ok("ip", &["route", "replace", cidr, "dev", tun], None)?;
            return Ok(());
        }
        Err(anyhow!(
            "`ip route add {cidr} dev {tun}` failed: {}",
            out.stderr.trim()
        ))
    }

    fn set_dns(&mut self, tun: &str, cfg: &TunnelConfig) -> Result<()> {
        let dns = cfg.dns.to_string();
        if self.succeeds("resolvectl", &["status"]) {
            tracing::info!(tun, %dns, "configuring DNS via systemd-resolved");
            self.run_ok("resolvectl", &["dns", tun, &dns], None)
                .context("resolvectl dns")?;
            // Anything past this point is undone by `resolvectl revert`.
            self.undo.push(Undo::ResolvectlDns {
                tun: tun.to_string(),
            });
            self.run_ok("resolvectl", &["domain", tun, "~."], None)
                .context("resolvectl domain")?;
            self.run_ok("resolvectl", &["default-route", tun, "yes"], None)
                .context("resolvectl default-route")?;
            return Ok(());
        }

        tracing::info!(%dns, "systemd-resolved not running; rewriting {RESOLV_CONF}");
        if self.succeeds("test", &["-e", RESOLV_BACKUP]) {
            tracing::warn!(
                "{RESOLV_BACKUP} already exists (left by a previous run); keeping it as the original"
            );
        } else {
            self.run_ok("cp", &["-f", RESOLV_CONF, RESOLV_BACKUP], None)
                .context("backing up resolv.conf")?;
        }
        // Registered before writing so a failed write still restores the backup.
        self.undo.push(Undo::ResolvConf);
        let contents = resolv_conf_contents(cfg.dns);
        self.run_ok("tee", &[RESOLV_CONF], Some(&contents))
            .context("writing resolv.conf")?;
        Ok(())
    }
}

impl<R: CommandRunner> PlatformConfigurator for LinuxConfigurator<R> {
    fn apply(
        &mut self,
        tun_name: &str,
        cfg: &TunnelConfig,
        routes: &RouteMode,
        set_dns: bool,
    ) -> Result<()> {
        if !self.reverted {
            self.revert()?;
        }
        self.undo.clear();
        self.reverted = false;

        self.ensure_address(tun_name, cfg)?;
        for cidr in route_cidrs(routes) {
            self.add_route(&cidr, tun_name)?;
            self.undo.push(Undo::Route {
                cidr,
                tun: tun_name.to_string(),
            });
        }
        if set_dns {
            self.set_dns(tun_name, cfg)?;
        }
        Ok(())
    }

    fn revert(&mut self) -> Result<()> {
        if self.reverted {
            return Ok(());
        }
        self.reverted = true;
        let mut first_err: Option<anyhow::Error> = None;
        while let Some(step) = self.undo.pop() {
            let res = match &step {
                Undo::ResolvectlDns { tun } => self
                    .run_ok("resolvectl", &["revert", tun], None)
                    .map(|_| ()),
                Undo::ResolvConf => self
                    .run_ok("cp", &["-f", RESOLV_BACKUP, RESOLV_CONF], None)
                    .and_then(|_| self.run_ok("rm", &["-f", RESOLV_BACKUP], None))
                    .map(|_| ()),
                Undo::Route { cidr, tun } => self
                    .run_ok("ip", &["route", "del", cidr, "dev", tun], None)
                    .map(|_| ()),
            };
            if let Err(e) = res {
                tracing::warn!(?step, error = %e, "revert step failed");
                first_err.get_or_insert(e);
            }
        }
        match first_err {
            Some(e) => Err(e),
            None => Ok(()),
        }
    }
}

impl<R: CommandRunner> Drop for LinuxConfigurator<R> {
    fn drop(&mut self) {
        if !self.reverted {
            tracing::warn!("configurator dropped without revert; reverting now");
            if let Err(e) = self.revert() {
                tracing::error!(error = %e, "best-effort revert on drop failed");
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use std::net::Ipv4Addr;
    use std::sync::{Arc, Mutex};

    use super::*;
    use crate::platform::{CommandOutput, RecordedCommand, RecordingRunner};

    fn cfg() -> TunnelConfig {
        TunnelConfig::default()
    }

    fn argvs(rec: &[RecordedCommand]) -> Vec<String> {
        rec.iter().map(|r| r.argv()).collect()
    }

    const IP_ADDR_SHOW: &str = "\
5: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1400 qdisc fq_codel state UNKNOWN group default qlen 500
    inet 10.77.0.2 peer 10.77.0.1/24 scope global tun0
       valid_lft forever preferred_lft forever
";

    /// Runner where tun-rs already assigned the address and systemd-resolved
    /// is running.
    fn runner_resolved() -> (RecordingRunner, Arc<Mutex<Vec<RecordedCommand>>>) {
        let r = RecordingRunner {
            responses: vec![
                (
                    ("ip".into(), "-4".into()),
                    CommandOutput {
                        success: true,
                        stdout: IP_ADDR_SHOW.into(),
                        stderr: String::new(),
                    },
                ),
                (
                    ("resolvectl".into(), "status".into()),
                    CommandOutput {
                        success: true,
                        stdout: "Global\n  Protocols: +LLMNR +mDNS\n".into(),
                        stderr: String::new(),
                    },
                ),
            ],
            ..Default::default()
        };
        let log = r.log.clone();
        (r, log)
    }

    #[test]
    fn full_mode_with_resolved_dns_command_sequence() {
        let (runner, log) = runner_resolved();
        let mut c = LinuxConfigurator::new(runner);
        c.apply("tun0", &cfg(), &RouteMode::Full, true).unwrap();
        assert_eq!(
            argvs(&log.lock().unwrap()),
            vec![
                "ip -4 addr show dev tun0",
                "ip link set dev tun0 mtu 9000 up",
                "ip route add 0.0.0.0/1 dev tun0",
                "ip route add 128.0.0.0/1 dev tun0",
                "resolvectl status",
                "resolvectl dns tun0 10.77.0.1",
                "resolvectl domain tun0 ~.",
                "resolvectl default-route tun0 yes",
            ]
        );

        c.revert().unwrap();
        assert_eq!(
            argvs(&log.lock().unwrap()[8..]),
            vec![
                "resolvectl revert tun0",
                "ip route del 128.0.0.0/1 dev tun0",
                "ip route del 0.0.0.0/1 dev tun0",
            ]
        );

        // Second revert and drop are no-ops.
        c.revert().unwrap();
        assert_eq!(log.lock().unwrap().len(), 11);
        drop(c);
        assert_eq!(log.lock().unwrap().len(), 11);
    }

    #[test]
    fn custom_mode_without_dns_sets_address_when_missing() {
        // Default runner: `ip -4 addr show` returns empty stdout.
        let runner = RecordingRunner::default();
        let log = runner.log.clone();
        let mut c = LinuxConfigurator::new(runner);
        let routes = RouteMode::Custom(vec![
            "1.1.1.1/32".parse().unwrap(),
            "8.8.8.8/32".parse().unwrap(),
            "192.168.50.77/24".parse().unwrap(), // host bits are truncated
        ]);
        let mut tc = cfg();
        tc.mtu = 1380;
        tc.prefix_len = 30;
        c.apply("tun3", &tc, &routes, false).unwrap();
        assert_eq!(
            argvs(&log.lock().unwrap()),
            vec![
                "ip -4 addr show dev tun3",
                "ip addr add 10.77.0.2 peer 10.77.0.1/30 dev tun3",
                "ip link set dev tun3 mtu 1380 up",
                "ip route add 1.1.1.1/32 dev tun3",
                "ip route add 8.8.8.8/32 dev tun3",
                "ip route add 192.168.50.0/24 dev tun3",
            ]
        );
        c.revert().unwrap();
        assert_eq!(
            argvs(&log.lock().unwrap()[6..]),
            vec![
                "ip route del 192.168.50.0/24 dev tun3",
                "ip route del 8.8.8.8/32 dev tun3",
                "ip route del 1.1.1.1/32 dev tun3",
            ]
        );
    }

    #[test]
    fn resolv_conf_fallback_when_resolved_missing() {
        // `resolvectl status` fails (not installed / not running) and no
        // stale backup exists (`test -e` fails).
        let mut runner = RecordingRunner::default();
        runner.failing.push("resolvectl status".into());
        runner.failing.push("test -e".into());
        let log = runner.log.clone();
        let mut c = LinuxConfigurator::new(runner);
        let routes = RouteMode::Custom(vec!["1.1.1.1/32".parse().unwrap()]);
        c.apply("tun1", &cfg(), &routes, true).unwrap();
        let rec = log.lock().unwrap().clone();
        assert_eq!(
            argvs(&rec),
            vec![
                "ip -4 addr show dev tun1",
                "ip addr add 10.77.0.2 peer 10.77.0.1/24 dev tun1",
                "ip link set dev tun1 mtu 9000 up",
                "ip route add 1.1.1.1/32 dev tun1",
                "resolvectl status",
                "test -e /etc/resolv.conf.netm-backup",
                "cp -f /etc/resolv.conf /etc/resolv.conf.netm-backup",
                "tee /etc/resolv.conf",
            ]
        );
        let written = rec[7].stdin.as_deref().unwrap();
        assert!(written.contains("nameserver 10.77.0.1\n"), "{written}");
        assert!(written.contains(RESOLV_BACKUP));

        c.revert().unwrap();
        assert_eq!(
            argvs(&log.lock().unwrap()[8..]),
            vec![
                "cp -f /etc/resolv.conf.netm-backup /etc/resolv.conf",
                "rm -f /etc/resolv.conf.netm-backup",
                "ip route del 1.1.1.1/32 dev tun1",
            ]
        );
    }

    #[test]
    fn stale_resolv_backup_is_kept() {
        // `test -e <backup>` succeeds: the backup from a crashed run is the
        // real original and must not be overwritten.
        let mut runner = RecordingRunner::default();
        runner.failing.push("resolvectl status".into());
        let log = runner.log.clone();
        let mut c = LinuxConfigurator::new(runner);
        c.apply("tun1", &cfg(), &RouteMode::Custom(vec![]), true)
            .unwrap();
        let rec = argvs(&log.lock().unwrap());
        assert!(!rec.iter().any(|a| a.starts_with("cp -f /etc/resolv.conf ")));
        assert_eq!(rec.last().unwrap(), "tee /etc/resolv.conf");
        c.revert().unwrap();
        let rec = argvs(&log.lock().unwrap());
        assert_eq!(
            &rec[rec.len() - 2..],
            &[
                "cp -f /etc/resolv.conf.netm-backup /etc/resolv.conf",
                "rm -f /etc/resolv.conf.netm-backup",
            ]
        );
    }

    #[test]
    fn drop_reverts_when_not_reverted() {
        let (runner, log) = runner_resolved();
        {
            let mut c = LinuxConfigurator::new(runner);
            c.apply("tun0", &cfg(), &RouteMode::Full, true).unwrap();
            assert_eq!(log.lock().unwrap().len(), 8);
        }
        let rec = argvs(&log.lock().unwrap());
        assert_eq!(rec.len(), 11, "drop must run the revert steps");
        assert_eq!(rec[8], "resolvectl revert tun0");
        assert_eq!(rec[9], "ip route del 128.0.0.0/1 dev tun0");
        assert_eq!(rec[10], "ip route del 0.0.0.0/1 dev tun0");
    }

    #[test]
    fn failed_route_aborts_apply_and_reverts_partial_state() {
        let mut runner = RecordingRunner::default();
        runner.failing.push("ip route add 128.0.0.0/1".to_string());
        let log = runner.log.clone();
        let mut c = LinuxConfigurator::new(runner);
        let err = c.apply("tun1", &cfg(), &RouteMode::Full, true).unwrap_err();
        assert!(err.to_string().contains("128.0.0.0/1"), "{err}");
        c.revert().unwrap();
        let rec = argvs(&log.lock().unwrap());
        assert_eq!(rec.last().unwrap(), "ip route del 0.0.0.0/1 dev tun1");
        assert!(!rec.iter().any(|a| a.starts_with("resolvectl")));
    }

    #[test]
    fn existing_route_is_replaced() {
        let runner = RecordingRunner {
            responses: vec![(
                ("ip".into(), "route".into()),
                CommandOutput {
                    success: false,
                    stdout: String::new(),
                    stderr: "RTNETLINK answers: File exists".into(),
                },
            )],
            ..Default::default()
        };
        let log = runner.log.clone();
        // Every `ip route ...` call fails with "exists", so the replace fails
        // too and apply reports an error...
        let mut c = LinuxConfigurator::new(runner);
        let routes = RouteMode::Custom(vec!["1.1.1.1/32".parse().unwrap()]);
        assert!(c.apply("tun1", &cfg(), &routes, false).is_err());
        // ...but it must have attempted `ip route replace`.
        let rec = argvs(&log.lock().unwrap());
        assert_eq!(
            &rec[rec.len() - 2..],
            &[
                "ip route add 1.1.1.1/32 dev tun1",
                "ip route replace 1.1.1.1/32 dev tun1",
            ]
        );
    }

    #[test]
    fn ip_addr_inet_detection() {
        assert!(ip_addr_has_inet(IP_ADDR_SHOW, Ipv4Addr::new(10, 77, 0, 2)));
        assert!(!ip_addr_has_inet(IP_ADDR_SHOW, Ipv4Addr::new(10, 77, 0, 1)));
        let plain = "3: tun0: <...>\n    inet 10.77.0.22/24 scope global tun0\n";
        assert!(ip_addr_has_inet(plain, Ipv4Addr::new(10, 77, 0, 22)));
        assert!(!ip_addr_has_inet(plain, Ipv4Addr::new(10, 77, 0, 2)));
        assert!(!ip_addr_has_inet("", Ipv4Addr::new(10, 77, 0, 2)));
    }

    #[test]
    fn route_lists() {
        assert_eq!(
            route_cidrs(&RouteMode::Full),
            vec!["0.0.0.0/1", "128.0.0.0/1"]
        );
        assert_eq!(
            route_cidrs(&RouteMode::Custom(vec!["10.1.2.3/16".parse().unwrap()])),
            vec!["10.1.0.0/16"]
        );
    }
}
